// ── Types ──────────────────────────────────────────────────────────

// ── Collaborators ─────────────────────────────────────────────────
export const COLLABORATORS = [
  {
    id: "c1",
    name: "Rohit Chugh",
    avatar: "https://i.pravatar.cc/150?u=rohit",
    role: "owner",
    online: true,
    email: "rohit@collabide.dev",
  },
  {
    id: "c2",
    name: "Priya Anand",
    avatar: "https://i.pravatar.cc/150?u=priya",
    role: "editor",
    online: true,
    email: "priya@collabide.dev",
  },
  {
    id: "c3",
    name: "Arjun Kapoor",
    avatar: "https://i.pravatar.cc/150?u=arjun",
    role: "editor",
    online: true,
    email: "arjun@collabide.dev",
  },
  {
    id: "c4",
    name: "Sneha Rao",
    avatar: "https://i.pravatar.cc/150?u=sneha",
    role: "viewer",
    online: false,
    email: "sneha@collabide.dev",
  },
  {
    id: "c5",
    name: "Dev Mehta",
    avatar: "https://i.pravatar.cc/150?u=dev",
    role: "editor",
    online: true,
    email: "dev@collabide.dev",
  },
  {
    id: "c6",
    name: "Kiran Bose",
    avatar: "https://i.pravatar.cc/150?u=kiran",
    role: "viewer",
    online: false,
    email: "kiran@collabide.dev",
  },
  {
    id: "c7",
    name: "Aisha Mirza",
    avatar: "https://i.pravatar.cc/150?u=aisha",
    role: "editor",
    online: true,
    email: "aisha@collabide.dev",
  },
  {
    id: "c8",
    name: "Rahul Singh",
    avatar: "https://i.pravatar.cc/150?u=rahul",
    role: "viewer",
    online: false,
    email: "rahul@collabide.dev",
  },
];

const [rohit, priya, arjun, sneha, dev, kiran, aisha, rahul] = COLLABORATORS;

// ── Projects ──────────────────────────────────────────────────────
export const PROJECTS = [
  {
    id: "p1",
    name: "acme-dashboard",
    description:
      "Internal analytics dashboard for Acme Corp — real-time KPIs, charts, and team reporting.",
    language: "JavaScript",
    collaborators: [rohit, priya, arjun, sneha, dev],
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    starred: true,
    archived: false,
    runs: 14,
    shared: false,
  },
  {
    id: "p2",
    name: "ml-experiments",
    description:
      "Collection of ML experiments — classification models, LLM fine-tuning, and data pipelines.",
    language: "Python",
    collaborators: [rohit, aisha],
    updatedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
    starred: true,
    archived: false,
    runs: 31,
    shared: true,
  },
  {
    id: "p3",
    name: "portfolio-v3",
    description:
      "Personal portfolio site — built with Next.js 14, Framer Motion, and a custom CMS.",
    language: "JavaScript",
    collaborators: [rohit],
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    starred: false,
    archived: false,
    runs: 7,
    shared: false,
  },
  {
    id: "p4",
    name: "microservices-gateway",
    description:
      "API gateway for internal microservices — rate limiting, auth middleware, request routing.",
    language: "Go",
    collaborators: [rohit, arjun, kiran],
    updatedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    starred: true,
    archived: false,
    runs: 22,
    shared: false,
  },
  {
    id: "p5",
    name: "design-system",
    description:
      "Component library and design tokens shared across all frontend projects at scale.",
    language: "JavaScript",
    collaborators: [rohit, priya, sneha, rahul],
    updatedAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
    starred: false,
    archived: false,
    runs: 5,
    shared: true,
  },
  {
    id: "p6",
    name: "cli-toolkit",
    description:
      "A blazing-fast CLI toolkit for scaffolding, deployment, and environment management.",
    language: "Rust",
    collaborators: [rohit, dev],
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    starred: false,
    archived: false,
    runs: 9,
    shared: false,
  },
  {
    id: "p7",
    name: "blog-cms",
    description:
      "Headless CMS for the engineering blog — markdown + MDX support, editor preview.",
    language: "MDX",
    collaborators: [rohit, priya],
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 100 * 86400000).toISOString(),
    starred: false,
    archived: false,
    runs: 2,
    shared: false,
  },
  {
    id: "p8",
    name: "event-service",
    description:
      "Event-driven microservice using Kafka and Spring Boot for real-time notifications.",
    language: "Java",
    collaborators: [rohit, arjun, aisha, dev, kiran],
    updatedAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 50 * 86400000).toISOString(),
    starred: false,
    archived: false,
    runs: 18,
    shared: true,
  },
  {
    id: "p9",
    name: "landing-page",
    description:
      "Marketing landing page with animated hero, feature sections, and pricing table.",
    language: "JavaScript",
    collaborators: [rohit, sneha],
    updatedAt: new Date(Date.now() - 8 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    starred: false,
    archived: false,
    runs: 3,
    shared: false,
  },
  {
    id: "p10",
    name: "auth-service",
    description:
      "Centralised authentication service — JWT, OAuth2, MFA, and session management.",
    language: "JavaScript",
    collaborators: [rohit, arjun],
    updatedAt: new Date(Date.now() - 18 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 35 * 86400000).toISOString(),
    starred: true,
    archived: false,
    runs: 11,
    shared: false,
  },
  {
    id: "p11",
    name: "data-pipeline",
    description:
      "ETL pipeline for ingesting and transforming large datasets from multiple sources.",
    language: "Python",
    collaborators: [rohit, aisha, rahul],
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 70 * 86400000).toISOString(),
    starred: false,
    archived: false,
    runs: 26,
    shared: true,
  },
  {
    id: "p12",
    name: "old-monolith",
    description:
      "Legacy monolith being gradually migrated to microservices. Archived for reference.",
    language: "Java",
    collaborators: [rohit],
    updatedAt: new Date(Date.now() - 30 * 86400000).toISOString(),
    createdAt: new Date(Date.now() - 365 * 86400000).toISOString(),
    starred: false,
    archived: true,
    runs: 0,
    shared: false,
  },
];

// ── Activity ──────────────────────────────────────────────────────
export const ACTIVITIES = [
  {
    id: "a1",
    collaborator: priya,
    action: "edited",
    target: "Header.jsx",
    timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: "a2",
    collaborator: arjun,
    action: "pushed to",
    target: "main branch",
    timestamp: new Date(Date.now() - 28 * 60000).toISOString(),
  },
  {
    id: "a3",
    collaborator: dev,
    action: "commented on",
    target: "auth-service PR",
    timestamp: new Date(Date.now() - 55 * 60000).toISOString(),
  },
  {
    id: "a4",
    collaborator: aisha,
    action: "created",
    target: "ml-experiments",
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: "a5",
    collaborator: rohit,
    action: "starred",
    target: "design-system",
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: "a6",
    collaborator: sneha,
    action: "opened",
    target: "landing-page",
    timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: "a7",
    collaborator: kiran,
    action: "reviewed",
    target: "microservices PR #14",
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: "a8",
    collaborator: rahul,
    action: "edited",
    target: "README.md",
    timestamp: new Date(Date.now() - 7 * 3600000).toISOString(),
  },
  {
    id: "a9",
    collaborator: priya,
    action: "merged",
    target: "feat/dashboard PR",
    timestamp: new Date(Date.now() - 9 * 3600000).toISOString(),
  },
  {
    id: "a10",
    collaborator: arjun,
    action: "deployed",
    target: "acme-dashboard",
    timestamp: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: "a11",
    collaborator: dev,
    action: "created",
    target: "cli-toolkit",
    timestamp: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: "a12",
    collaborator: aisha,
    action: "ran",
    target: "ml-experiments pipeline",
    timestamp: new Date(Date.now() - 1.5 * 86400000).toISOString(),
  },
  {
    id: "a13",
    collaborator: sneha,
    action: "invited",
    target: "Rahul Singh",
    timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "a14",
    collaborator: rohit,
    action: "archived",
    target: "old-monolith",
    timestamp: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: "a15",
    collaborator: kiran,
    action: "forked",
    target: "design-system",
    timestamp: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
];
