import type { editor } from 'monaco-editor'

export const COLLAB_IDE_THEME: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'EDEDF0', background: '0E0E12' },
    { token: 'comment', foreground: '5C5C68', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'A78BFA', fontStyle: 'bold' },
    { token: 'identifier', foreground: 'EDEDF0' },
    { token: 'string', foreground: '34D399' },
    { token: 'number', foreground: 'F59E0B' },
    { token: 'delimiter', foreground: '828292' },
    { token: 'type', foreground: '38BDF8', fontStyle: 'bold' },
    { token: 'type.identifier', foreground: '38BDF8' },
    { token: 'function', foreground: '60A5FA' },
    { token: 'tag', foreground: 'F472B6' },
    { token: 'attribute.name', foreground: 'FBBF24' },
    { token: 'attribute.value', foreground: '34D399' },
    { token: 'variable', foreground: 'E2E8F0' },
    { token: 'constant', foreground: 'F87171' },
  ],
  colors: {
    'editor.background': '#0E0E12',
    'editor.foreground': '#EDEDF0',
    'editorCursor.foreground': '#7C5CFF',
    'editor.lineHighlightBackground': '#17171E',
    'editorLineNumber.foreground': '#4B4B58',
    'editorLineNumber.activeForeground': '#A78BFA',
    'editor.selectionBackground': '#7C5CFF33',
    'editor.inactiveSelectionBackground': '#7C5CFF18',
    'editorWhitespace.foreground': '#252530',
    'editorIndentGuide.background1': '#1F1F2A',
    'editorIndentGuide.activeBackground1': '#3D3D52',
    'editorBracketMatch.background': '#7C5CFF25',
    'editorBracketMatch.border': '#7C5CFF80',
    'minimap.background': '#0E0E12',
    'scrollbarSlider.background': '#28283660',
    'scrollbarSlider.hoverBackground': '#3D3D5090',
    'scrollbarSlider.activeBackground': '#7C5CFF80',
  },
}
