export const TEMPLATES_DATA = [
  {
    id: "react-vite",
    name: "React + Vite",
    slug: "react-vite-starter",
    description:
      "Blazing-fast frontend starter featuring React 19, JavaScript, Vite HMR, and Tailwind CSS.",
    category: "Frontend",
    tags: ["React", "JavaScript", "Tailwind", "Vite"],
    stars: "18.2k",
    usedBy: "34.8k developers",
    gradient: "from-cyan-500/20 via-blue-600/20 to-indigo-600/30",
    accentColor: "#38BDF8",
    iconName: "React",
  },
  {
    id: "nextjs-14",
    name: "Next.js 14",
    slug: "nextjs-app-router",
    description:
      "Fullstack production template with App Router, Server Components, API routes, and Lucide icons.",
    category: "Fullstack",
    tags: ["Next.js", "React", "JavaScript", "Tailwind"],
    stars: "24.5k",
    usedBy: "52.1k developers",
    gradient: "from-zinc-400/20 via-neutral-700/30 to-black/50",
    accentColor: "#E2E8F0",
    iconName: "Nextjs",
  },
  {
    id: "nodejs-api",
    name: "Node.js API",
    slug: "nodejs-rest-api",
    description:
      "Clean REST API boilerplate with JavaScript, native Node HTTP, Zod validation, and Jest testing.",
    category: "Backend",
    tags: ["Node.js", "JavaScript", "Zod", "Jest"],
    stars: "9.4k",
    usedBy: "18.9k developers",
    gradient: "from-emerald-500/20 via-green-600/20 to-teal-800/30",
    accentColor: "#10B981",
    iconName: "Node",
  },
  {
    id: "express-mongo",
    name: "Express + MongoDB",
    slug: "express-mongodb-app",
    description:
      "Scalable backend with Express, Mongoose ODM, JWT authentication, and structured error handlers.",
    category: "Backend",
    tags: ["Express", "MongoDB", "Node.js", "JWT"],
    stars: "14.1k",
    usedBy: "27.4k developers",
    gradient: "from-green-600/20 via-emerald-700/20 to-lime-900/30",
    accentColor: "#22C55E",
    iconName: "Express",
  },
  {
    id: "python-flask",
    name: "Python Flask",
    slug: "python-flask-service",
    description:
      "Lightweight Python microservice with Flask 3, SQLAlchemy ORM, and automated OpenAPI documentation.",
    category: "Backend",
    tags: ["Python", "Flask", "SQLAlchemy", "REST"],
    stars: "11.8k",
    usedBy: "19.2k developers",
    gradient: "from-sky-500/20 via-blue-600/20 to-indigo-900/30",
    accentColor: "#60A5FA",
    iconName: "Python",
  },
  {
    id: "django-rest",
    name: "Django REST",
    slug: "django-rest-framework",
    description:
      "Batteries-included API framework with Django REST, token authentication, and SQLite/Postgres support.",
    category: "Backend",
    tags: ["Django", "Python", "DRF", "PostgreSQL"],
    stars: "16.7k",
    usedBy: "22.6k developers",
    gradient: "from-teal-600/20 via-emerald-800/20 to-cyan-950/40",
    accentColor: "#14B8A6",
    iconName: "Django",
  },
  {
    id: "vanilla-html",
    name: "Vanilla HTML/CSS/JS",
    slug: "vanilla-web-starter",
    description:
      "Zero dependencies, pure web standards with semantic HTML5, modern CSS variables, and ES modules.",
    category: "Learning",
    tags: ["HTML5", "CSS3", "JavaScript", "No-Build"],
    stars: "6.2k",
    usedBy: "14.1k developers",
    gradient: "from-orange-500/20 via-amber-600/20 to-red-800/30",
    accentColor: "#F97316",
    iconName: "HTML",
  },
  {
    id: "vue-3",
    name: "Vue 3",
    slug: "vue3-composition-starter",
    description:
      "Modern Vue 3 application with Vite, Composition API, Pinia state store, and Vue Router 4.",
    category: "Frontend",
    tags: ["Vue 3", "JavaScript", "Pinia", "Vite"],
    stars: "13.9k",
    usedBy: "21.5k developers",
    gradient: "from-emerald-400/20 via-teal-600/20 to-green-900/30",
    accentColor: "#34D399",
    iconName: "Vue",
  },
  {
    id: "sveltekit",
    name: "Svelte Kit",
    slug: "sveltekit-modern",
    description:
      "High performance fullstack web apps with Svelte 5 runes, SSR, file-based routing, and adapter-node.",
    category: "Fullstack",
    tags: ["SvelteKit", "Svelte", "JavaScript", "Vite"],
    stars: "10.3k",
    usedBy: "15.8k developers",
    gradient: "from-orange-600/20 via-red-600/20 to-rose-900/30",
    accentColor: "#FB923C",
    iconName: "Svelte",
  },
  {
    id: "static-site-11ty",
    name: "Static Site (11ty)",
    slug: "eleventy-static-blog",
    description:
      "Simple yet powerful static site generator using Eleventy, Markdown content, and fast compile times.",
    category: "Static",
    tags: ["11ty", "Markdown", "Static Site", "SEO"],
    stars: "5.1k",
    usedBy: "8.7k developers",
    gradient: "from-purple-500/20 via-violet-600/20 to-indigo-900/30",
    accentColor: "#A855F7",
    iconName: "Eleventy",
  },
  {
    id: "rust-cli",
    name: "Rust CLI",
    slug: "rust-cargo-cli",
    description:
      "Blazing fast command-line binary with Cargo workspace, Clap argument parser, and colored outputs.",
    category: "Backend",
    tags: ["Rust", "Cargo", "Clap", "CLI"],
    stars: "15.4k",
    usedBy: "12.4k developers",
    gradient: "from-amber-600/20 via-orange-700/20 to-red-950/40",
    accentColor: "#F59E0B",
    iconName: "Rust",
  },
  {
    id: "go-web-server",
    name: "Go Web Server",
    slug: "go-gin-api-server",
    description:
      "High throughput concurrent microservice using Go 1.22, Gin HTTP framework, and Docker multi-stage build.",
    category: "Backend",
    tags: ["Go", "Gin", "Docker", "Concurrency"],
    stars: "17.3k",
    usedBy: "26.1k developers",
    gradient: "from-cyan-400/20 via-sky-600/20 to-blue-900/30",
    accentColor: "#22D3EE",
    iconName: "Go",
  },
];
